### ISSUE TITLE
Upgrade to Django 3.0

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSEAdmin#105]
Django 3.0 is now available. 

https://www.djangoproject.com/weblog/2019/dec/02/django-3-released/

With the release of Django 3.0, Django 2.2 has reached the end of 
mainstream support. The final minor bug fix release (which is also a 
security release), 2.2.8, was issued on 2019-12-02. Django 2.2 is an LTS release and
will receive security and data loss fixes until April 2022. All users are 
encouraged to upgrade before then to continue receiving fixes for 
security issues. 

See the downloads page [1] for a table of supported versions and the 
future release schedule. 

[1] https://www.djangoproject.com/download/#supported-versions

**Comment by mondus** [comment]
Simple change in `toml` file and an updated `requirements.txt`. `Readme` also updated for details on how to generate `requirements.txt`.

**Comment by willfurnass** [comment]
No deprecation warnings?  Great!
