### ISSUE TITLE
Unable to delete time sheet entry until page is refreshed

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSEAdmin#118]
After adding a time sheet entry, atempting to delete the entry will result in an errror modal until the page has been refreshed.

Steps to reproduce:
1. Go to Timesheet page
2. Create an all day even via dragging
3. Select the new entry
4. Attempt to delete -> Error.
5. Refresh
6. Select the entry
7. Delete -> Success

timesheet.html#L297
![image](https://user-images.githubusercontent.com/628937/72744251-1a977e80-3ba5-11ea-9b31-81352d6f0794.png)

**Comment by mondus** [comment]
Hmmm interesting.

**Comment by mondus** [comment]
Bug I introduced in recent commit (JS error so not reaching branch where calendar is refreshed)
