### ISSUE TITLE
Dragging projects to extend in timesheets results in error

### ISSUE THREAD

**Issue by davidwilby** [RSE-Sheffield/RSEAdmin#119]
![Screenshot from 2020-01-21 09-17-53](https://user-images.githubusercontent.com/24752124/72792152-6c391b00-3c30-11ea-8a98-1d4ea9a5519c.png)

When dragging a project to extend across multiple days, this error is produced. Similarly for multiple hours across a day etc.
May be related to this particular project, I'm not sure, this is the only one I can allocate.

**Comment by mondus** [comment]
This is not supported. Events can only be for a single day.

**Comment by mondus** [comment]
Error message can however be improved

**Comment by mondus** [comment]
Multiple hours per day should however work and does on my test site
