### ISSUE TITLE
Github Actions waiting for a runner to pick up jobs

### ISSUE THREAD

**Issue by yld-weng** [RSE-Sheffield/RSEAdmin#220]
After some research, it appears that the os used in the CI is deprecated since April 2023.

https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by yld-weng** [comment]
https://github.com/RSE-Sheffield/RSEAdmin/commit/28fd0edd80bc2ac6184d7a2b8f4cf8fbf34c1bdf

**Comment by willfurnass** [comment]
Yeah, testing against 22.04 makes sense, particularly given that that's what we're using in production
