### ISSUE TITLE
Some (not all) data tables disappear on certain browser widths

### ISSUE THREAD

**Issue by mondus** [RSE-Sheffield/RSEAdmin#78]
E.g. Happens with projects view if window width is reduced or on mobile display. Maybe a boostrap issue but probably not.

**Comment by mondus** [comment]
Incorrect mixing of bootstrap `col-xs` and `col-md`. All are reverted to `col-md`. New issue #92 created for checking display on mobile browsers.

**Comment by willfurnass** [comment]
NB we need a pic for the ReadTheDocs site of a RSE team lead doing some team admin on their iPhone on a train.
